'use strict';
const request = require('request');
module.exports = function (app) {
    var abc = require("../Controllers/com_con");
    app
        .route("/Data")
        .get(abc.listData)
        .post(abc.postData)
    app
        .route("/equal")
        .get(abc.equal)
    app
        .route("/greater")
        .get(abc.greater)
    app
        .route("/greaterEqual")
        .get(abc.greaterEqual)
    app
        .route("/equalarray")
        .get(abc.in)
    app
        .route("/less")
        .get(abc.less)
    app
        .route("/equalless")
        .get(abc.equalless)
    app
        .route("/notequal")
        .get(abc.notequal)
    app
        .route("/notpresent")
        .get(abc.notpresent)
    app
        .route("/andopt")
        .get(abc.andopt)
    app
        .route("/notopt")
        .get(abc.notopt)
    app
        .route("/noropt")
        .get(abc.noropt)
    app
        .route("/oropt")
        .get(abc.oropt)
    app
        .route("/exists")
        .get(abc.exists)
    app
        .route("/type")
        .get(abc.type)
    app
        .route("/expression")
        .get(abc.expression)
    app
        .route("/regex")
        .get(abc.regex)
    app
        .route("/text")
        .get(abc.text)
    app
        .route("/all")
        .get(abc.all)
    app
        .route("/elemMatch")
        .get(abc.elemMatch)
    app
        .route("/size")
        .get(abc.size)
    app
        .route("/rating")
        .post(abc.rating)
    app
        .route("/avgRate")
        .get(abc.avgRate)
    app
        .route("/postRef")
        .post(abc.postRef)
    app
        .route("/coin")
        .get(abc.coin)
    app
        .route("/coinid")
        .get(abc.coinid)
    app
        .route("/notcoin")
        .get(abc.notcoin)
    app
        .route("/listCoin")
        .get(abc.listCoin)
    app
        .route("/CoinRef")
        .get(abc.CoinRef)
    app
        .route("/BcryptSignup")
        .get(abc.bcryptSignup)
    app
        .route("/BcryptLogin")
        .get(abc.bcryptLogin)
    // app
    // .route("/tri")
    // .post(abc.abc)
    app
        .route("/age1")
        .post(abc.student)
    app
        .route("/age2")
        .get(abc.stdRef)
    app
        .route("/khelaao")
        .post(abc.khelaaoapi)
        .get(abc.listkhelaao)
}